### ISSUE TITLE
TypeError: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by slorber** [thlorenz/exorcist#21]
This works:

```javascript
gulp.task('exorcist-test', function() {
    browserify({ debug: true })
        .add("intl")
        .bundle()
        .on('error', handleErrors)
        .pipe(source('appPolyfills.js'))
        .on('error', handleErrors)
        .pipe(exorcist("testmap"))
        .on('error', handleErrors)
        .pipe(fs.createWriteStream(path.join(__dirname, 'bundle.js'), 'utf8'));
});
```

But this does not:

```javascript
gulp.task('exorcist-test', function() {
    browserify({ debug: true })
        .add("intl")
        .bundle()
        .on('error', handleErrors)
        .pipe(source('appPolyfills.js'))
        .on('error', handleErrors)
        .pipe(exorcist("testmap"))
        .on('error', handleErrors)
        .pipe(gulp.dest('./build'));
});
```

```
path.js:439
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at DestroyableTransform.saveFile [as _transform] (/home/sebastien/Desktop/Stample-react/node_modules/gulp/node_modules/vinyl-fs/lib/dest/index.js:36:26)
    at DestroyableTransform.Transform._read (/home/sebastien/Desktop/Stample-react/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/sebastien/Desktop/Stample-react/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/sebastien/Desktop/Stample-react/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/sebastien/Desktop/Stample-react/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/home/sebastien/Desktop/Stample-react/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:107:17)
    at drain (/home/sebastien/Desktop/Stample-react/node_modules/exorcist/node_modules/mold-source-map/node_modules/through/index.js:35:16)
```

I have tried with 2 different versions of NodeJS 0.10.24 and 0.12.5, both throw the error.

Notice that I have found other issues related in other projects that use the "through" stream library.
See https://github.com/adam-lynch/gulp-bless/issues/2

**Comment by slorber** [comment]
I don't know what exactly is the problem but it may be related to source (vinyl-source-stream)

This seems to works fine:

```
    browserify({ debug: true })
        .add("intl")
        .bundle()
        .pipe(exorcist("./build/appPolyfills.map.js"))
        .pipe(source('appPolyfills.js'))
        .pipe(gulp.dest('./build'));
```

**Comment by slorber** [comment]
Note I also have some troubles to integrate uglify before exorcist.

I piped this before: `streamify(uglify());`

I replaced this with `uglifyify` transform and finally got it working correctly.

Example build for those encountering the same problems:


```
gulp.task('browserify-polyfills', ['cleanJs'], function() {
    var b = browserify({
        debug: includeSourceMaps
    });
    if ( uglifyFiles ) {
        b.transform("uglifyify",{global:true});
    }
    polyfills.forEach(function(polyfill) {
        b.add(polyfill);
    });
    return b.bundle()
        .pipe(gulpif(includeSourceMaps,exorcist("./build/appPolyfills.map.js")))
        .pipe(source('appPolyfills.js'))
        .pipe(gulp.dest('./build'));
});
```

**Comment by bendrucker** [comment]
Closing this because it's not an exorcist issue and more of a gotcha of using vinyl streams/gulp
